#!/usr/bin/env ruby
require_relative 'config/application'
require_relative 'app/controllers/controller'

class Router
  attr_reader :controller
  def initialize(argv)
    @controller = Controller.new
    self.route(argv)
  end
  def route(argv)
    command = argv.shift
    params = argv
    case command
    # when 'get' then controller.new_cow #=> reset db?
    when 'feed' then controller.feed
    when 'check' then controller.check
    when 'milk' then controller.milk
    when 'procreate' then controller.milk
    else  controller.man
    end
  end

end

router = Router.new(ARGV)
